onBuy:
  sendCommand:
    use: false
    command: "pxe mail {OwnerName} &aVous avez vendu &3 {Amount} &ex&3{ItemName} &aà &d{BuyerName} &apour &e{ItemPrice} &6Suns &aà l'hôtel des ventes"

expiration:
  time: 3600 #In seconds
  checkEvery: 72000 #In ticks
limitations:
  default: 5
  paysan: 10
  marchand: 15
  terrien: 20
  citoyen: 25
  commercant: 30
  citadin: 35
min-price:
  COBBLESTONE: 0.5