global:
  lang: "en"
  orderBy: "ASC" # ASC or DESC / ASC : More recent to older / DESC : Older to more recent
  dateFormat: "dd/MM/yyyy ':' HH:mm"
  securityForSpammingPacket: true
  min-price: # Min price per item. Ex : 1 CobbleStone at 0.5. Set {} to disable it
    COBBLESTONE: 0.5
  expiration:
    checkEvery: 72000 #In ticks
auction:
  onBuy:
    sendCommand: # Command sends if item is buying
      use: false
      command: ""
  expiration:
    time: 86400 #In seconds
  limitations: # Number of auction per rank
    default: 5
bid:
  onBuy:
    sendMessage: # Command sends if item is buying
      use: false
      command: ""
  expiration:
    time: 86400 #In seconds
  limitations: # Number of auction per rank
    default: 5
