name: FAuction
main: fr.florianpal.fauction.FAuction
author: florianpal
version: 1.9.0
api-version: 1.13
softdepend: [Vault]
permissions:
  fauction.user:
    default: op
    children:
      fauction.list: true
      fauction.sell: true
      fauction.expire: true